### ISSUE TITLE
A few quick questions about testing

### ISSUE THREAD

**Issue by maotouxiaohei** [CRazorback/AADG#12] opened 2023-12-05 08:14 UTC
Hello, I didn't find the test file that loaded the training weight in the process of reproducing the code. I wrote a test code myself, but it didn't feel very good, could you please open source related test split code?

**Comment by maotouxiaohei** [comment] 2023-12-13 08:10
Excuse me, I don't know how the AADG-segmented image in Figure 3 got the result because I couldn't find the code in the test.py file，and which weight file should I choose to test, final_model_state.pth or the model_best.pth?  Could you tell me how to load this weight file, thank you.

**Comment by CRazorback** [comment] 2023-12-13 08:16
Hi,

Thank you for your interest in our work.

We are using model_best.pth for inference. You can refer to the previous issue for details.

The pretrained weights and inference codes will be released in a few days for better reproducibility. I am happy to let you know once they are available.

Best,
Junyan

________________________________

**Comment by maotouxiaohei** [comment] 2023-12-13 08:23
Thank you very much, that will help a lot.

**Comment by CRazorback** [comment] 2023-12-20 13:19
Thank you for your waiting.

The visualization code has been released. You may refer to test.py. Unfortunately, I did not find the previous pre-trained models. I will train for new ones once I am available. Nevertheless, you may easily reproduce the quantitative results since we repeated the training multiple times and reported the mean values to avoid randomness.

**Closed as completed** 2024-03-12 03:17 UTC
